CREATE TABLE 'cat' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'name' TEXT(55) DEFAULT NULL,
'owner' TEXT(50) DEFAULT NULL,
'medicationYN' INTEGER(1) DEFAULT NULL,
'medicationDetails' TEXT(255) DEFAULT NULL,
'diet' TEXT(255) DEFAULT NULL,
'likesDislikes' TEXT(255) DEFAULT NULL,
'behaviourYN' INTEGER DEFAULT NULL,
'behaviourDetails' TEXT(255) DEFAULT NULL,
'other' TEXT(255) DEFAULT NULL,
'dateEntered' TEXT DEFAULT CURRENT_TIMESTAMP,
'dateLeaving' TEXT(40) DEFAULT NULL,
'inCattery' INTEGER(1) DEFAULT 1
);

CREATE TABLE 'cat_owner' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'id_cat' INTEGER DEFAULT NULL REFERENCES 'cat' ('id'),
'id_owner' INTEGER DEFAULT NULL REFERENCES 'owner' ('id')
);

CREATE TABLE 'users' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'username' TEXT DEFAULT NULL,
'email' TEXT DEFAULT NULL,
'password' TEXT DEFAULT NULL
);

CREATE TABLE 'owner' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'name' TEXT(55) DEFAULT NULL,
'address' TEXT(80) DEFAULT NULL,
'phoneNumber' TEXT(20) DEFAULT NULL,
'email' TEXT(80) DEFAULT NULL
);