CREATE TABLE 'Accounts' (
'id' INTEGER DEFAULT 1 PRIMARY KEY AUTOINCREMENT,
'name' TEXT(50) DEFAULT 'empty',
'total' INTEGER(25) DEFAULT 0,
'percent_in' INTEGER(10) DEFAULT 0,
'flat_in' INTEGER(25) DEFAULT 0
);